name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  kill_application:
  
#    runs-on: self-hosted
    
#    steps:
    
#    - name: kill application
#      run: taskkill /IM RabbitMQFinalProduct.exe /F
      
  build:

    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
#    - name: run finalproduct
#      run: C:\actions-runner\_work\Planning\Planning\RabbitMQFinalProduct\bin\Debug\netcoreapp3.1\RabbitMQFinalProduct.exe
#      shell: powershell -command "& '{0}'"
#    - name: Dotnet Publish
#      run: dotnet publish src -c Release -o deploy
    - name: add vpn connection
      run: Add-VpnConnection -Name "EhB" -ServerAddress "dtsslvpn.ehb.be" -TunnelType "Sstp" -EncryptionLevel "Optional" -AuthenticationMethod Eap -Force -RememberCredential -PassThru
    - name: connect to vpn
      run: rasdial ehb  ${{secrets.VPN}}
