name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  kill_application:
  
#    runs-on: self-hosted
    
#    steps:
    
#    - name: kill application
#      run: taskkill /IM RabbitMQFinalProduct.exe /F
      
  build:

    runs-on: windows-latest

    steps:
    
#    - uses: actions/checkout@v2
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.x
#    - name: Restore dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
#    - name: run finalproduct
#      run: C:\actions-runner\_work\Planning\Planning\RabbitMQFinalProduct\bin\Debug\netcoreapp3.1\RabbitMQFinalProduct.exe
#      shell: powershell -command "& '{0}'"
#    - name: Dotnet Publish
#      run: dotnet publish src -c Release -o deploy
    - name: add vpn connection
      shell: pwsh
      run: |
        Add-VpnConnection -Name "EHB_VPN" -ServerAddress "dtsslvpn.ehb.be" -TunnelType "SSTP" -AllUserConnection -Force
        rasdial EHB_VPN  ${{secrets.VPN}}
#    - name: ls -a via ssh
#      uses: fifsky/ssh-action@master
#      with:
#        command: |
#          cd /tmp
#          ls -a
#        host: ${{ secrets.SSH_CONNECTION }}
#        user: ${{ secrets.SSH_USER }}
#        key: ${{ secrets.SSH_PASSWORD }}
#    - name: install posh-ssh
#      shell: powershell
#      run: Install-Module -Name Posh-SSH -Force
#    - name: Add info to posh-ssh
#      shell: powershell
#      run: |
#        $secpasswd = ConvertTo-SecureString ${{ secrets.SSH_PASSWORD }} -AsPlainText -Force
#        $Credentials = New-Object System.Management.Automation.PSCredential -ArgumentList ${{ secrets.SSH_USER }}, $secpasswd

#        $SessionID = New-SSHSession -ComputerName ${{ secrets.SSH_CONNECTION }} -Credential $Credentials -AcceptKey:$true
#    - name: Try a command
#      run: Invoke-SSHCommand -Index $sessionid.sessionid -Command "echo hello world" # Invoke Command Over SSH
    - name: Run Commands via SSH To Start/Stop
      uses: Flaavius/ssh-commands@1.0
      with:
        command: sh service.sh
        host: ${{ secrests.SSH_CONNECTION }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        tryKeyboard: true
